apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: html
  template:
    metadata:
      labels:
        app: html
    spec:
      containers:
      - name: html
        image: ai8998aiatpl/agola:latest
        ports:
        - containerPort: 3000  # Port your application listens on